/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authDashboardRouteImport } from './routes/(auth)/dashboard'
import { Route as authUserInfoRouteImport } from './routes/(auth)/user/info'
import { Route as authUserEditRouteImport } from './routes/(auth)/user/edit'
import { Route as authPostsNewRouteImport } from './routes/(auth)/posts/new'
import { Route as authPostsListRouteImport } from './routes/(auth)/posts/list'
import { Route as authPostsPostSeqRouteImport } from './routes/(auth)/posts/$postSeq'
import { Route as authPostsEditPostSeqRouteImport } from './routes/(auth)/posts/edit/$postSeq'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authDashboardRoute = authDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authRouteRoute,
} as any)
const authUserInfoRoute = authUserInfoRouteImport.update({
  id: '/user/info',
  path: '/user/info',
  getParentRoute: () => authRouteRoute,
} as any)
const authUserEditRoute = authUserEditRouteImport.update({
  id: '/user/edit',
  path: '/user/edit',
  getParentRoute: () => authRouteRoute,
} as any)
const authPostsNewRoute = authPostsNewRouteImport.update({
  id: '/posts/new',
  path: '/posts/new',
  getParentRoute: () => authRouteRoute,
} as any)
const authPostsListRoute = authPostsListRouteImport.update({
  id: '/posts/list',
  path: '/posts/list',
  getParentRoute: () => authRouteRoute,
} as any)
const authPostsPostSeqRoute = authPostsPostSeqRouteImport.update({
  id: '/posts/$postSeq',
  path: '/posts/$postSeq',
  getParentRoute: () => authRouteRoute,
} as any)
const authPostsEditPostSeqRoute = authPostsEditPostSeqRouteImport.update({
  id: '/posts/edit/$postSeq',
  path: '/posts/edit/$postSeq',
  getParentRoute: () => authRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof authDashboardRoute
  '/posts/$postSeq': typeof authPostsPostSeqRoute
  '/posts/list': typeof authPostsListRoute
  '/posts/new': typeof authPostsNewRoute
  '/user/edit': typeof authUserEditRoute
  '/user/info': typeof authUserInfoRoute
  '/posts/edit/$postSeq': typeof authPostsEditPostSeqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof authDashboardRoute
  '/posts/$postSeq': typeof authPostsPostSeqRoute
  '/posts/list': typeof authPostsListRoute
  '/posts/new': typeof authPostsNewRoute
  '/user/edit': typeof authUserEditRoute
  '/user/info': typeof authUserInfoRoute
  '/posts/edit/$postSeq': typeof authPostsEditPostSeqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(auth)/dashboard': typeof authDashboardRoute
  '/(auth)/posts/$postSeq': typeof authPostsPostSeqRoute
  '/(auth)/posts/list': typeof authPostsListRoute
  '/(auth)/posts/new': typeof authPostsNewRoute
  '/(auth)/user/edit': typeof authUserEditRoute
  '/(auth)/user/info': typeof authUserInfoRoute
  '/(auth)/posts/edit/$postSeq': typeof authPostsEditPostSeqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/posts/$postSeq'
    | '/posts/list'
    | '/posts/new'
    | '/user/edit'
    | '/user/info'
    | '/posts/edit/$postSeq'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/posts/$postSeq'
    | '/posts/list'
    | '/posts/new'
    | '/user/edit'
    | '/user/info'
    | '/posts/edit/$postSeq'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(auth)/dashboard'
    | '/(auth)/posts/$postSeq'
    | '/(auth)/posts/list'
    | '/(auth)/posts/new'
    | '/(auth)/user/edit'
    | '/(auth)/user/info'
    | '/(auth)/posts/edit/$postSeq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/dashboard': {
      id: '/(auth)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authDashboardRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/user/info': {
      id: '/(auth)/user/info'
      path: '/user/info'
      fullPath: '/user/info'
      preLoaderRoute: typeof authUserInfoRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/user/edit': {
      id: '/(auth)/user/edit'
      path: '/user/edit'
      fullPath: '/user/edit'
      preLoaderRoute: typeof authUserEditRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/posts/new': {
      id: '/(auth)/posts/new'
      path: '/posts/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof authPostsNewRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/posts/list': {
      id: '/(auth)/posts/list'
      path: '/posts/list'
      fullPath: '/posts/list'
      preLoaderRoute: typeof authPostsListRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/posts/$postSeq': {
      id: '/(auth)/posts/$postSeq'
      path: '/posts/$postSeq'
      fullPath: '/posts/$postSeq'
      preLoaderRoute: typeof authPostsPostSeqRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/posts/edit/$postSeq': {
      id: '/(auth)/posts/edit/$postSeq'
      path: '/posts/edit/$postSeq'
      fullPath: '/posts/edit/$postSeq'
      preLoaderRoute: typeof authPostsEditPostSeqRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authDashboardRoute: typeof authDashboardRoute
  authPostsPostSeqRoute: typeof authPostsPostSeqRoute
  authPostsListRoute: typeof authPostsListRoute
  authPostsNewRoute: typeof authPostsNewRoute
  authUserEditRoute: typeof authUserEditRoute
  authUserInfoRoute: typeof authUserInfoRoute
  authPostsEditPostSeqRoute: typeof authPostsEditPostSeqRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authDashboardRoute: authDashboardRoute,
  authPostsPostSeqRoute: authPostsPostSeqRoute,
  authPostsListRoute: authPostsListRoute,
  authPostsNewRoute: authPostsNewRoute,
  authUserEditRoute: authUserEditRoute,
  authUserInfoRoute: authUserInfoRoute,
  authPostsEditPostSeqRoute: authPostsEditPostSeqRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
